import Link from "next/link";
import LegalLayout from "../components/LegalLayout";

export default function PrivacyPolicy() {
  return (
    <LegalLayout title="Privacy Policy" updated="August 31, 2026">
      <p>
        This Privacy Policy explains what data Career Platform ("we", "us", "our")
        collects, how we use it, and the choices you have. It applies to the
        career-development services available through this platform.
      </p>

      <H2>Information we collect</H2>
      <p>
        When you use the platform, we collect the information you provide and the
        information generated as you use our services, including:
      </p>
      <ul className="list-disc space-y-1 pl-5">
        <li>
          <strong>Account data</strong> — your email address and a securely hashed
          password when you register.
        </li>
        <li>
          <strong>Profile data</strong> — information you upload or connect,
          including resume documents, LinkedIn data, and GitHub data. We use these
          to build your skill profile and generate gap analyses, roadmaps, and
          interview feedback.
        </li>
        <li>
          <strong>Practice &amp; assessment data</strong> — coding challenge
          submissions, mock interview sessions, and feedback generated by AI.
        </li>
        <li>
          <strong>Usage data</strong> — records of the AI features you use, the
          models called, and token usage. We use this to meter usage, maintain our
          free tier, and manage billing.
        </li>
        <li>
          <strong>Payment data</strong> — if you purchase credits, payment
          processing is handled by our third-party processor (Stripe). We do not
          store your full card details on our servers.
        </li>
      </ul>

      <H2>How we use your information</H2>
      <p>We use your information to:</p>
      <ul className="list-disc space-y-1 pl-5">
        <li>Provide, operate, and improve the career-development services;</li>
        <li>Generate personalized skill-gap analyses, roadmaps, coding practice, and interview feedback;</li>
        <li>Enforce free-tier limits, meter usage, and process credit purchases;</li>
        <li>Secure your account and prevent fraud or abuse;</li>
        <li>Send service-related notices (we do not sell your personal data).</li>
      </ul>

      <H2>AI processing</H2>
      <p>
        Some features use large-language models via a third-party provider
        (OpenRouter) to produce analyses and feedback. The profile content you
        submit and the features you run may be sent to that provider solely to
        generate your results. We meter token usage and store the associated cost
        for billing and free-tier purposes.
      </p>

      <H2>Data sharing</H2>
      <p>
        We do not sell your personal data. We share data only with service
        providers that help us operate the platform (for example, hosting,
        storage, secure payment processing, and the AI provider), and only to the
        extent needed to provide the services. We may disclose information where
        required by law or to protect the rights, safety, and property of our
        users and the public.
      </p>

      <H2>Data retention &amp; your choices</H2>
      <p>
        We retain your data for as long as your account is active or as needed to
        provide the services and comply with legal obligations. You may update or
        delete your profile data from within the platform, and you may request
        deletion of your account and associated data by contacting us. You can
        revoke a connected GitHub or LinkedIn integration at any time.
      </p>

      <H2>Security</H2>
      <p>
        We use administrative, technical, and physical safeguards designed to
        protect your data, including encryption in transit and at rest for
        sensitive fields such as credentials and connected tokens. No method of
        transmission or storage is completely secure, and we cannot guarantee
        absolute security.
      </p>

      <H2>Children</H2>
      <p>
        The service is intended for users who are at least 16 years old (or the age
        of majority in their jurisdiction). We do not knowingly collect personal
        data from children. If you believe a child has provided us personal data,
        please contact us so we can delete it.
      </p>

      <H2>Changes to this policy</H2>
      <p>
        We may update this Privacy Policy from time to time. When we do, we will
        revise the "Last updated" date above. Continued use of the service after
        changes take effect constitutes acceptance of the revised policy.
      </p>

      <p>
        By creating an account you also agree to our{" "}
        <Link href="/terms" className="font-semibold text-blue-400 underline-offset-2 hover:underline">
          Terms of Service
        </Link>
        .
      </p>
    </LegalLayout>
  );
}

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mt-8 border-b border-white/10 pb-2 text-xl font-semibold text-white first:mt-0">
      {children}
    </h2>
  );
}
