import Link from "next/link";
import LegalLayout from "../components/LegalLayout";

export default function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service" updated="August 31, 2026">
      <p>
        These Terms of Service ("Terms") govern your access to and use of the
        Career Platform service. By creating an account or using the service, you
        agree to these Terms. If you do not agree, do not use the service.
      </p>

      <H2>1. The service</H2>
      <p>
        The service provides AI-assisted career-development tools for students,
        including skill-gap analysis, learning roadmaps, coding practice, mock
        interviews, communication feedback, and resume, LinkedIn, and GitHub
        analysis. Artificial-intelligence outputs are provided for informational
        purposes and may contain errors; they are not professional or career
        advice.
      </p>

      <H2>2. Eligibility</H2>
      <p>
        You must be at least 16 years old (or the age of majority in your
        jurisdiction) to use the service. By using it you represent that you meet
        this requirement and that you will comply with these Terms.
      </p>

      <H2>3. Your account</H2>
      <p>
        You are responsible for safeguarding your account credentials and for all
        activity under your account. You must provide accurate information. If you
        connect third-party accounts (such as GitHub or LinkedIn), you authorize us
        to access that data as described in our Privacy Policy and in line with
        that provider's permissions.
      </p>

      <H2>4. Acceptable use</H2>
      <p>You agree not to:</p>
      <ul className="list-disc space-y-1 pl-5">
        <li>Use the service for any unlawful purpose or in violation of applicable law;</li>
        <li>Attempt to gain unauthorized access, probe, or interfere with the service, its systems, or other users;</li>
        <li>Abuse usage limits or interfere with the service;</li>
        <li>Upload malicious content or content you do not have the right to process;</li>
        <li>Reverse engineer, copy, or resell the service or its outputs except as permitted.</li>
      </ul>

      <H2>5. AI service usage</H2>
      <p>
        The platform currently provides its AI-assisted career features without
        payment processing or credit purchases. We may apply reasonable usage
        limits to protect service availability and prevent abuse.
      </p>

      <H2>6. AI outputs</H2>
      <p>
        Solutions, analyses, roadmaps, and feedback are generated by AI and are
        provided "as is" without warranties of accuracy or completeness. You are
        responsible for verifying any output before relying on it, and you remain
        responsible for content you submit or submit for processing.
      </p>

      <H2>7. Intellectual property</H2>
      <p>
        The service, including its software, design, and branding, is owned by us
        and protected by intellectual-property laws. You retain ownership of the
        profile content you provide. You grant us a limited license to process and
        store your content solely to provide the service.
      </p>

      <H2>8. Termination</H2>
      <p>
        You may stop using the service at any time and may request deletion of your
        account. We may suspend or terminate access for violations of these Terms,
        fraudulent or abusive activity, or as required by law.
      </p>

      <H2>9. Disclaimers</H2>
      <p>
        The service is provided "as is" and "as available" without warranties of
        any kind, whether express or implied, including fitness for a particular
        purpose and non-infringement. To the maximum extent permitted by law, we do
        not warrant that the service will be uninterrupted, error-free, or that
        results will be accurate or reliable.
      </p>

      <H2>10. Limitation of liability</H2>
      <p>
        To the maximum extent permitted by law, we are not liable for any indirect,
        incidental, special, consequential, or punitive damages, or for any loss of
        profits or data, arising out of or related to your use of the service. Our
        aggregate liability is limited to the amount you paid for the service in the
        twelve (12) months preceding the claim.
      </p>

      <H2>11. Governing law</H2>
      <p>
        These Terms are governed by the laws applicable in our jurisdiction,
        without regard to conflict-of-law principles. You agree to the exclusive
        jurisdiction of the competent courts for any dispute arising from these
        Terms, subject to any mandatory consumer-protection rights you may have.
      </p>

      <H2>12. Changes to these Terms</H2>
      <p>
        We may update these Terms from time to time. Material changes will be
        reflected by an updated "Last updated" date. Continued use of the service
        after changes take effect constitutes acceptance of the revised Terms.
      </p>

      <p>
        Your use of the platform is also governed by our{" "}
        <Link href="/privacy" className="font-semibold text-blue-400 underline-offset-2 hover:underline">
          Privacy Policy
        </Link>
        .
      </p>
    </LegalLayout>
  );
}

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mt-8 border-b border-white/10 pb-2 text-xl font-semibold text-white first:mt-0">
      {children}
    </h2>
  );
}
