/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as CodingRouteImport } from './routes/coding'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RoadmapRouteImport } from './routes/roadmap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingRoute = CodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/coding': typeof CodingRoute
  '/companies': typeof CompaniesRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/coding': typeof CodingRoute
  '/companies': typeof CompaniesRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/coding': typeof CodingRoute
  '/companies': typeof CompaniesRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/coding'
    | '/companies'
    | '/interview'
    | '/login'
    | '/mentor'
    | '/profile'
    | '/register'
    | '/resume'
    | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/coding'
    | '/companies'
    | '/interview'
    | '/login'
    | '/mentor'
    | '/profile'
    | '/register'
    | '/resume'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/coding'
    | '/companies'
    | '/interview'
    | '/login'
    | '/mentor'
    | '/profile'
    | '/register'
    | '/resume'
    | '/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  CodingRoute: typeof CodingRoute
  CompaniesRoute: typeof CompaniesRoute
  InterviewRoute: typeof InterviewRoute
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResumeRoute: typeof ResumeRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding': {
      id: '/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  CodingRoute: CodingRoute,
  CompaniesRoute: CompaniesRoute,
  InterviewRoute: InterviewRoute,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResumeRoute: ResumeRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
